### ISSUE TITLE
What is an 'appropriate' Unicode code point?

### ISSUE THREAD

**Issue by r12a** [w3c/uievents#119] opened 2016-12-16 14:09 UTC
5.3.6. Guidelines for selecting key values
https://w3c.github.io/uievents/#keys-guidelines

> If the key generates a printable character, and there exists an appropriate Unicode code point, then the key attribute MUST be a string consisting of the char value of that character.

What constitutes an 'appropriate' Unicode code point here?  Is it 'something other than tab or linefeed'?  Or is it a code point that is not a control character? Or perhaps a code point that is defined in Unicode?

**Comment by asmusf** [comment] 2016-12-16 18:38
I would expect that this was intended to means that the character is encoded in Unicode and the expected return consists of what Unicode calls the "scalar value". However, the text seems to imply that only characters encoded via single code points can be assigned to a key. If that is the intended restriction, it should be spelled out more explicitly.

**Comment by garykac** [comment] 2017-01-25 00:34
Fixed

**Closed by garykac** 2017-01-25 00:34 UTC
Labels: i18n-comment
