### ISSUE TITLE
Expose modern 'wheel' event parameters (inertial scrolling, direction inversion)

### ISSUE THREAD

**Issue by atebits** [w3c/uievents#56] opened 2015-11-11 01:31 UTC
Copied from https://www.w3.org/Bugs/Public/show_bug.cgi?id=29276

Current DOM 'wheel' events only expose bare-minimum data (deltaX, deltaY) that don't fully capture how modern scrollwheels and trackpads behave.

Exposing two additional pieces of information would greatly improve the possibilities for interesting and important custom event handling.

1. Inertial-scroll events. For example, on many modern trackpads, "throwing" your fingers results in two distinct phases of scrolling. First, while your fingers are in contact with the trackpad *real* scroll events are delivered corresponding to your finger motion. Second, once your finger(s) leave the surface, a stream of scroll events are *synthesized* corresponding to the velocity of your fingers at the end of phase I.

For many applications it is vital to be able to distinguish between *real* and *synthetic* scroll events (e.g. to perform custom scroll handling with different physics parameters or boundary cases, where naive system-provided friction falloff will not suffice). Native event APIs expose this information and I propose that browsers could expose it through new WheelEvent properties.

Developers have come up with horrible hacks to work around not having this information (see https://libraries.io/npm/lethargy and weep).

2. Direction-inversion. Users may "invert" the direction of scrolling (conceptually the "page" moves in the same direction as their fingers vs. the "scrollbar" moves in the same direction as their fingers). Unfortunately this setting is not exposed to developers, and it would be useful to know whether given scroll deltas mirrored the users real-world finger motion.

Again, native APIs expose this information, and it would be extremely useful to have access to it in the browser in cases where scrolling gestures are interpreted as something other than 2D scrolling, (3D navigation for example).

If I may humbly propose exposing a few additional properties on delivered DOM wheel events:

    interface WheelEvent : MouseEvent {
    ...
    +    readonly    attribute boolean       isInertialScrolling;
    +    readonly    attribute boolean       directionInvertedFromDevice;
    };

isInertialScrolling of type boolean, readonly
  true if the event is the result of a synthetic inertial native scroll event
  false otherwise
directionInvertedFromDevice of type boolean, readonly
  true if the signs of deltaX and deltaY are reverse the user's physical scrolling direction
  false otherwise

**Comment by grorg** [comment] 2015-11-11 16:56
WebKit is interested in implementing this.

**Comment by hober** [comment] 2015-11-11 21:08
Should we break this into multiple issues, one per proposal?

**Comment by travisleithead** [comment] 2015-11-11 21:13
I think the ```directionInvertedFromDevice``` concept is much more straightforward. The inertial scrolling thing may be a bit tricker to get right--I'm not sure what we've got is necessarily going to solve the use cases...
Splitting them up may be a good idea :)

**Comment by masayuki-nakano** [comment] 2015-11-12 04:37
IIRC, whether a wheel event is caused by inertial scrolling (called momentum scrolling in Mozilla) can be distinguished only on Mac. So, I don't think that it's useful for web developers...

**Comment by atebits** [comment] 2015-11-12 15:48
@hober @travisleithead Thanks, split up: https://github.com/w3c/uievents/issues/57 https://github.com/w3c/uievents/issues/58

@masayuki-nakano True, though the other way to look at it is there are lots of kinds of inputs that may not be available on every platform. Right click doesn't make sense on touch devices, and touch events don't make sense if you don't have a touchscreen. But there are still APIs for those. I think progressive enhancement beats lowest-common-denominator.

**Comment by travisleithead** [comment] 2015-11-17 23:49
Closing, since we have this tracked now in #57 and #58

**Closed by travisleithead** 2015-11-17 23:49 UTC
Labels: Future Idea
