### ISSUE TITLE
definition of MouseEvent.clientX and clientY seems wrong

### ISSUE THREAD

**Issue by allan-bonadio** [w3c/uievents#339] opened 2022-12-30 02:38 UTC
Hi!  Thanks for your hard work on the standards for the web!

I think I've found some typos in this page, at this location:
https://w3c.github.io/uievents/#dom-mouseevent-clientx

It says:
clientX, of type long, readonly
The horizontal coordinate at which the event occurred relative to the viewport ...

clientY, of type long, readonly
The vertical coordinate at which the event occurred relative to the viewport...

I believe that, instead of viewport, it should say the component (either the target or probably currentTarget).  In fact, this example on the Mozilla site demonstrates it:

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientY#examples

**Comment by mustaqahmed** [comment] 2023-01-03 16:23
I believe the spec is correct.  The MDN example is within an `iframe` in the page, so the `clientX/Y` coordinates appear to be relative to that `iframe`.  The viewport there is perhaps the bound of the `iframe`---@bokand can confirm if this is the case.

**Comment by bokand** [comment] 2023-01-03 16:36
That's correct - The main window and each iframe establish their own [viewport](https://drafts.csswg.org/css2/#viewport) and the client coordinates are relative to that; so I agree with @mustaqahmed

**Comment by mustaqahmed** [comment] 2023-01-03 16:56
Thanks @bokand for confirming.  Does this call for a note in the viewport spec? Your comment "the main window and each iframe establish their own viewport" is more developer friendly IMHO than the spec text you pointed to.

The UIEvents spec is "working as intended", so closing the issue.

**Closed by mustaqahmed** 2023-01-03 16:56 UTC

**Comment by bokand** [comment] 2023-01-03 19:42
I wouldn't be opposed to making it clearer :)

**Comment by allan-bonadio** [comment] 2023-01-04 04:47
OK, I get it.  I thought Client was doing what Offset is doing: coordinates relative to the element it's in.  yeah, really, the MDN demo is misleading as it is, there isn't even a boundary line.  I should go bother them instead.  Or, just go change it myself.  Thanks for looking at this and straightening me out!
