### ISSUE TITLE
Update focusin/focusout event order to match implementations?

### ISSUE THREAD

**Issue by devongovett** [w3c/uievents#276] opened 2020-08-26 03:14 UTC
I noticed that the [spec says](https://w3c.github.io/uievents/#event-type-focusin)

> This event type MUST be dispatched before the element is given focus. The event target MUST be the element which is about to receive focus. This event type is similar to focus, but is dispatched before focus is shifted, and does bubble.

However, I couldn't find a single implementation that behaves this way. In all browsers I tested `focusin` is fired *after* `focus`. Same is true of `blur` and `focusout`. Additionally, `document.activeElement` is already updated to the new element in the `focusin` handler.

Should the spec be updated to match implementations?

**Comment by saschanaz** [comment] 2021-01-23 23:27
It seems this is a duplicate of #88.

**Closed by saschanaz** 2021-01-23 23:27 UTC
