### ISSUE TITLE
mousemove and preventDefault()

### ISSUE THREAD

**Issue by annevk** [w3c/uievents#278] opened 2020-11-02 08:51 UTC
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1674658 and https://jsfiddle.net/zu0jpar2/ in particular this seems like some hacky way to prevent text selection in Chrome/Safari that does not work in Firefox. The specification just says that `mousemove` is cancelable, but doesn't describe what that means.

**Comment by saschanaz** [comment] 2021-01-13 04:15
I feel it shouldn't be cancelable because, as a comment in the bug says, the mouse move itself can't be canceled.

**Comment by annevk** [comment] 2021-01-13 07:10
Agreed, but that would require Chrome and Safari to change their implementation.

cc @rniwa @NavidZ

**Comment by NavidZ** [comment] 2021-01-13 15:10
cc @mustaqahmed

**Comment by mustaqahmed** [comment] 2021-01-13 19:17
We (Chromium) attempted to fix this behavior [twice](https://crbug.com/346473) already, in 2015 and 2018!  Compat problems forced us to revert in both cases!!

Interestingly, Safari didn't allow canceling mousemove until 2015 (or may be later), see the bug I linked above.  Curious what motivated Safari to introduce this.

**Comment by saschanaz** [comment] 2021-01-13 23:11
It seems [the second revert](https://bugs.chromium.org/p/chromium/issues/detail?id=878392) was due to Chrome's internal use, though.

**Comment by mbrodesser** [comment] 2021-02-11 10:15
According to the spec, a "mousemove" event has no default action. But a "mousedown" event has.
For the former to be consistent with the latter, the former should get a default action consisting of  _extending_ a possibly started selection.

That would match Chrome's and Firefox's behavior when `preventDefault()` is **not** called. Firefox would then have to follow Chrome's behavior of not extending the selection when `preventDefault()` was called.

AFAIK, Safari's behavior is the same as Chrome's.

**Comment by saschanaz** [comment] 2021-03-05 23:13
Seems the Firefox behavior has changed to match others 🙂

**Comment by mustaqahmed** [comment] 2021-03-08 15:49
@saschanaz Your comment on Jan 13 is correct, and I convinced myself we should retry removing the `mousemove` default in Chrome!  Do we know why Firefox decided to match Chrome???

**Comment by saschanaz** [comment] 2021-03-08 16:02
I think it was per https://github.com/w3c/uievents/issues/278#issuecomment-777337460. I still think it's hacky and `selectionchange` should be preferred instead 🤔. @mbrodesser

**Comment by mbrodesser** [comment] 2021-03-11 10:51
> I think it was per [#278 (comment)](https://github.com/w3c/uievents/issues/278#issuecomment-777337460).

Yes.

 I still think it's hacky and `selectionchange` should be preferred instead thinking. @mbrodesser

Sure, this can be changed. I agree that it would be cleaner. @rniwa: any concerns from your side?

**Comment by rniwa** [comment] 2021-03-12 05:18
> > I still think it's hacky and `selectionchange` should be preferred instead thinking. @mbrodesser
> 
> Sure, this can be changed. I agree that it would be cleaner. @rniwa: any concerns from your side?

Change what?

**Comment by mbrodesser** [comment] 2021-03-12 09:09
> > > I still think it's hacky and `selectionchange` should be preferred instead thinking. @mbrodesser
> > 
> > 
> > Sure, this can be changed. I agree that it would be cleaner. @rniwa: any concerns from your side?
> 
> Change what?

What's mentioned in https://github.com/w3c/uievents/issues/278#issuecomment-792846116.

**Comment by rniwa** [comment] 2021-03-12 09:13
What does "removing `mousemove` default" mean in this context? Making preventDefault on `mousemove` a no-op?

**Comment by annevk** [comment] 2021-03-12 10:02
Yeah.

**Comment by saschanaz** [comment] 2021-07-27 12:58
We at Mozilla found that this is not web compatible since [jQuery Mobile calls MouseEvent#preventDefault() on desktop browsers without expecting mousemove](https://github.com/jquery/jquery-mobile/issues/8670). We had to [restore our previous behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=1674658#c15) after getting regression reports.

We should probably prefer selectionchange event for this purpose and make mousemove not cancelable.

**Comment by justanotheranonymoususer** [comment] 2021-07-27 13:05
@saschanaz so how does it work with other browsers such as Chrome? There's probably other behavior difference of Firefox vs Chrome beyond the cancelability of mousemove?

**Comment by saschanaz** [comment] 2021-07-27 13:08
> @saschanaz so how does it work with other browsers such as Chrome? There's probably other behavior difference of Firefox vs Chrome beyond the cancelability of mousemove?

Yes, but [a weird bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1219471) in Chrome prevents canceling mousemove default action when CSS `transform: translate()` is used elsewhere on the page. So some websites basically are depending on that bug.

**Comment by mustaqahmed** [comment] 2022-12-06 20:52
> We at Mozilla found that this is not web compatible since [jQuery Mobile calls MouseEvent#preventDefault() on desktop browsers without expecting mousemove](https://github.com/jquery/jquery-mobile/issues/8670). We had to [restore our previous behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=1674658#c15) after getting regression reports.

I got confused with this today after seeing that the WPT is [passing](https://wpt.fyi/results/uievents/mouse/mousemove_prevent_default_action.tentative.html?label=master&label=experimental&aligned) in Chrome!  I think this is because the test ends too early before catching the Chrome problem.  Before I land [the change](https://chromium-review.googlesource.com/c/chromium/src/+/4081610), I wanted to double-check: @saschanaz you meant Mozilla now ignores `mosuemove` cancellation again, is this correct?

> We should probably prefer selectionchange event for this purpose and make mousemove not cancelable.

Unfortunately, the `selectionchange` event is [not cancelable](https://w3c.github.io/selection-api/#dfn-selectionchange)!  And I don't see any other candidate event that can possibly allow suppressing selection-extension.

**Comment by saschanaz** [comment] 2022-12-06 21:07
Weird, not sure what happened exactly, but [the test suddenly started to pass around October 2022 without any implementation change nor the test change](https://hg.mozilla.org/mozilla-central/log/tip/testing/web-platform/meta/uievents/mouse/mousemove_prevent_default_action.tentative.html.ini). I wonder any test harness change affected it.

**Comment by saschanaz** [comment] 2022-12-06 21:08
@jgraham might know what happened?

**Comment by jgraham** [comment] 2022-12-06 21:14
Looks like it was actually fixed in July by https://bugzilla.mozilla.org/show_bug.cgi?id=1543337

**Comment by saschanaz** [comment] 2022-12-06 22:06
That didn't touch ` testing/web-platform/meta/uievents/mouse/mousemove_prevent_default_action.tentative.html.ini`, no?

**Comment by saschanaz** [comment] 2022-12-06 22:27
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1804341

**Comment by mustaqahmed** [comment] 2023-10-13 14:31
Looking back at this issue after a while, I get a partial picture about compat problems with two orthogonal default actions of `mousemove`:
- Chrome couldn't fix `dragstart` default action:
https://bugs.chromium.org/p/chromium/issues/detail?id=346473#c34
- Mozilla couldn't fix `selectionchange` default action: https://github.com/w3c/uievents/issues/278#issuecomment-887490074

We need to check each event on Chrome, Firefox and Safari for a complete picture.

**Comment by saschanaz** [comment] 2024-05-08 22:05
Just noticed @mustaqahmed's Intent to Ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/fyVzOAmQHzU, I guess we can close this issue once Chrome ships it successfully.

**Comment by mustaqahmed** [comment] 2024-05-09 18:18
I agree we can close it.  Chrome is shipping it on M125 (Stable to be released in ~a week), and the WPT is [passing](https://wpt.fyi/results/uievents/mouse/mousemove_prevent_default_action.html?label=experimental&label=master&aligned) in all browsers.

**Closed by mustaqahmed** 2024-05-09 18:18 UTC
